version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data_init:/docker-entrypoint-initdb.d

  python_app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./game:/app
    ports:
      - "5000:5000"
    command: ["python", "/app/main.py"]
    environment:
      DB__USERNAME: postgres
      DB__PASSWORD: postgres
      DB__HOST: db
      DB__PORT: 5432
      DB__DATABASE: app
      DB__TYPE: postgresql
